"""initial schema

Revision ID: 3458e3990574
Revises: 
Create Date: 2026-02-26 18:39:18.894214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.models import FloatArrayType


# revision identifiers, used by Alembic.
revision: str = '3458e3990574'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('admin', 'user', name='usertype'), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('KM', 'H', name='vehiclecategory'), nullable=False),
    sa.Column('segment', sa.Integer(), nullable=False),
    sa.Column('samples_start_date', sa.Date(), nullable=False, comment='Data da primeira posição do array samples'),
    sa.Column('samples_end_date', sa.Date(), nullable=False, comment='Data da última posição do array samples'),
    sa.Column('upper', sa.Float(), nullable=False, comment='Percentil superior calculado sobre samples'),
    sa.Column('samples', FloatArrayType(), nullable=False, comment='Últimas N amostras (valores raw, pode conter zeros)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('samples_start_date <= samples_end_date', name='check_samples_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_segment', 'vehicles', ['category', 'segment'], unique=False)
    op.create_index(op.f('ix_vehicles_category'), 'vehicles', ['category'], unique=False)
    op.create_index(op.f('ix_vehicles_segment'), 'vehicles', ['segment'], unique=False)
    op.create_table('vehicle_summary_features',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('per_day', sa.Float(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('continuity_score', sa.Float(), nullable=False),
    sa.Column('active_weeks_rate', sa.Float(), nullable=False),
    sa.Column('active_days_rate', sa.Float(), nullable=False),
    sa.Column('gaps_cv', sa.Float(), nullable=False),
    sa.Column('mean_gap', sa.Float(), nullable=False),
    sa.Column('max_gap', sa.Float(), nullable=False),
    sa.Column('cv', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('iqr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('vehicle_weekday_features',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False, comment='Dia da semana: 1=seg, 2=ter, 3=qua, 4=qui, 5=sex, 6=sab, 7=dom'),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('iqr', sa.Float(), nullable=False),
    sa.Column('prob_active', sa.Float(), nullable=False),
    sa.Column('cv', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('day >= 1 AND day <= 7', name='check_valid_weekday'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id', 'day')
    )
    op.create_index('idx_vehicle_day', 'vehicle_weekday_features', ['vehicle_id', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vehicle_day', table_name='vehicle_weekday_features')
    op.drop_table('vehicle_weekday_features')
    op.drop_table('vehicle_summary_features')
    op.drop_index(op.f('ix_vehicles_segment'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_category'), table_name='vehicles')
    op.drop_index('idx_category_segment', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
