"""add profile_metadata table

Revision ID: 2979853d9c35
Revises: c06b817ceada
Create Date: 2026-04-27 11:26:36.311946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2979853d9c35'
down_revision: Union[str, Sequence[str], None] = 'c06b817ceada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_veiculos', sa.Integer(), nullable=False, comment='Quantidade de veículos no perfil'),
    sa.Column('dt_inicio', sa.Date(), nullable=False, comment='Primeira segunda-feira >= min(data)'),
    sa.Column('dt_fim', sa.Date(), nullable=False, comment='Última sexta-feira <= max(data)'),
    sa.Column('sample_size', sa.Integer(), nullable=False, comment='sample_size utilizado no trimming'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_metadata')
    # ### end Alembic commands ###
