"""add daily_activity_removed table

Revision ID: 6e66f3ee876a
Revises: 4f69f989c3fc
Create Date: 2026-04-27 17:35:21.565899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e66f3ee876a'
down_revision: Union[str, Sequence[str], None] = '4f69f989c3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity_removed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('veiculo_id', 'data', name='uq_daily_removed_veiculo_data')
    )
    op.create_index('idx_daily_removed_veiculo_data', 'daily_activity_removed', ['veiculo_id', 'data'], unique=False)
    op.create_index(op.f('ix_daily_activity_removed_veiculo_id'), 'daily_activity_removed', ['veiculo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_activity_removed_veiculo_id'), table_name='daily_activity_removed')
    op.drop_index('idx_daily_removed_veiculo_data', table_name='daily_activity_removed')
    op.drop_table('daily_activity_removed')
    # ### end Alembic commands ###
