"""add active_models table

Revision ID: 9ea8eb380bbe
Revises: 2979853d9c35
Create Date: 2026-04-27 11:48:14.865902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea8eb380bbe'
down_revision: Union[str, Sequence[str], None] = '2979853d9c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=2), nullable=False, comment="'km' ou 'h'"),
    sa.Column('filename', sa.String(length=256), nullable=False, comment='Nome do ficheiro ONNX vigente'),
    sa.Column('model_type', sa.String(length=20), nullable=False, comment="'multihead' ou 'moe'"),
    sa.Column('trained_at', sa.Date(), nullable=False, comment='Data em que o modelo foi gerado'),
    sa.Column('activated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target')
    )
    op.create_table('profile_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_veiculos', sa.Integer(), nullable=False, comment='Quantidade de veículos no perfil'),
    sa.Column('dt_inicio', sa.Date(), nullable=False, comment='Primeira segunda-feira >= min(data)'),
    sa.Column('dt_fim', sa.Date(), nullable=False, comment='Última sexta-feira <= max(data)'),
    sa.Column('sample_size', sa.Integer(), nullable=False, comment='sample_size utilizado no trimming'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_metadata')
    op.drop_table('active_models')
    # ### end Alembic commands ###
