# Re-exports para compatibilidade com imports legados.
# Usar os subpacotes diretamente em código novo:
#   from moviasai.profiling import ...
#   from moviasai.data import ...
#   from moviasai.forecasting import ...
